# Generated by Django 5.0.2 on 2024-04-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(to='biblioteca.genre'),
        ),
    ]
