# Generated by Django 5.0.2 on 2024-04-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='document',
            field=models.CharField(help_text='Tipo de documento', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='doc',
            field=models.CharField(help_text='Sigla del tipo de documento', max_length=5),
        ),
    ]
