# Generated by Django 5.0.2 on 2024-04-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_documenttype_document_alter_documenttype_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='doc',
            field=models.CharField(help_text='Sigla del tipo de documento', max_length=10),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='document',
            field=models.CharField(help_text='Tipo de documento', max_length=30, null=True),
        ),
    ]
