# Generated by Django 5.0.2 on 2024-04-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_documenttype_doc_alter_documenttype_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
