# Generated by Django 5.0.2 on 2024-04-11 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.documenttype'),
        ),
    ]
