# Generated by Django 5.0.2 on 2024-04-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('user', '0007_remove_user_likes_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(null=True, to='biblioteca.book'),
        ),
    ]
