# Generated by Django 5.0.2 on 2024-04-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('user', '0008_user_favorite_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(to='biblioteca.book'),
        ),
    ]
