# Generated by Django 5.0.2 on 2024-04-16 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_book_pdf'),
        ('user', '0009_alter_user_favorite_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.ForeignKey(blank=True, default='No especificado', on_delete=django.db.models.deletion.CASCADE, to='user.documenttype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ForeignKey(blank=True, default='No especificado', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genre'),
        ),
    ]
