# Generated by Django 5.0.2 on 2024-04-16 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_book_pdf'),
        ('user', '0010_alter_user_document_alter_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.documenttype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genre'),
        ),
    ]
